export enum ExceptionErrorCodes {
    E_INVALID_API_TOKEN = "E_INVALID_API_TOKEN",
    E_VALIDATION_FAILURE = "E_VALIDATION_FAILURE",
    E_INVALID_AUTH_UID = "E_INVALID_AUTH_UID",
    E_ROW_NOT_FOUND = "E_ROW_NOT_FOUND",
    E_PARAM_REQUIRED = "E_PARAM_REQUIRED",
}